{
 ### Environment Parameters
  debug: false,
  mode: train,
  cuda: true,
  pin_memory: true,
  wandb: false,
  worker: 8,
  log_interval: 9999,
  save_interval: 1,
  saved_model_directory: 'model_ckpts',
  train_fold: 1,
  project_name: 'U-NET',
  CUDA_VISIBLE_DEVICES: '0',

  ### Train Parameters
  model_name: 'UNet',
    n_classes: 1,
    in_channels: 1, # 3 for RGB, 4 for RGBA
  dataloader: 'Image2Image_zero_pad',
  # criterion: 'DiceBCELoss',
  criterion: 'DiceBCELoss', # DiceBCELoss
  task: 'segmentation',
  input_space: 'L',
  input_channel: 1,  # 3 for RGB, 4 for RGBA
  input_size: [600, 600],  # [h, w] DRIVE:608, STARE:704, CHASE_DB1:1024, HRF:1344
  optimizer: 'AdamW',
    lr: 0.001,
    scheduler: 'WarmupCosine',  # ConstantLRSchedule, WarmupCosine
    cycles: 100,
    warmup_epoch: 20,
    weight_decay: 0.05, # 0.05
  batch_size: 4,
  epoch: 500,
  ema_decay: 0, # set 0 to deactivate
  class_weight: [1.0, 1.0], model_path: '', # pretrained/FSG-Net-DRIVE.pt
    freeze_layer: false,

  ### Augmentation Parameters
  transform_blur: false,
  transform_jitter: false,
  transform_hflip: true,
  transform_perspective: false,
  transform_cutmix: false,
  transform_rand_resize: false,
  # transform_rand_crop: 288,
  transform_rand_crop: 150,


  train_x_path: '/content/drive/MyDrive/Prashant/FSG/Road_Extraction/data/data_fsr/train/input',
  train_y_path: '/content/drive/MyDrive/Prashant/FSG/Road_Extraction/data/data_fsr/train/label',
  val_x_path: '/content/drive/MyDrive/Prashant/FSG/Road_Extraction/data/data_fsr/val/input',
  val_y_path: '/content/drive/MyDrive/Prashant/FSG/Road_Extraction/data/data_fsr/val/label',

  # train_x_path: '/content/drive/MyDrive/Prashant/FSG/Road_Extraction/data/data_fsr/train/input',
  # train_y_path: '/content/drive/MyDrive/Prashant/FSG/Road_Extraction/data/data_fsr/train/label',
  # val_x_path: '/content/drive/MyDrive/Prashant/FSG/Road_Extraction/data/data_fsr/val/input',
  # val_y_path: '/content/drive/MyDrive/Prashant/FSG/Road_Extraction/data/data_fsr/val/label',

  # train_x_path: '/content/drive/MyDrive/Prashant/FSG/Road_Extraction/data/drive/train/input',
  # train_y_path: '/content/drive/MyDrive/Prashant/FSG/Road_Extraction/data/drive/train/label',
  # val_x_path: '/content/drive/MyDrive/Prashant/FSG/Road_Extraction/data/drive/val/input',
  # val_y_path: '/content/drive/MyDrive/Prashant/FSG/Road_Extraction/data/drive/val/label',
}
